### ISSUE TITLE
FakeBold in lualatex not allowing values below 1.5 ?

### ISSUE THREAD

**Issue by rallg** [latex3/fontspec#498]
## Description
FakeBold=1.05 produces same result as FakeBold=1.5 in lualatex. Unexpected. This was noticed by another user at https://tex.stackexchange.com/questions/708507/want-to-darken-a-font-just-a-little

## Check/indicate
- [ ] Relevant for XeTeX
- [ X] Relevant for LuaTeX
- [X ] Issue tracker has been searched for similar issues?
- [X ] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{Latin Modern Roman}
\begin{document}
hello\par
{\addfontfeature{FakeBold=1.05}hello}\par
{\addfontfeatuyre{FakeBold=1.5}hello}\par
\end{document}
```

## Further details
The second hello should be just slightly darker than the first. But actually, it is darkened more, to match the third. Does not matter which font (only used LMR for MWE). I do not recall this behavior in the past.

**Comment by khaledhosny** [comment]
A generated PDF from this example (there is a typo in the 2nd addfontfeature) shows slight difference in darkening between the 2nd and 3rd lines, amd the generated PDF has:
```
0.105 w
2 Tr
/F27 9.96264 Tf
1 0 0 1 148.712 695.17 Tm [<003F0032004800480051>]TJ
0.150 w
2 Tr
/F27 9.96264 Tf
1 0 0 1 148.712 683.215 Tm [<003F0032004800480051>]TJ
```

Notice the `0.105 w` and `0.150 w`, so the PDF has the correct values. Since the emboldening (actually stroking) is actually done by the PDF renderer, I don’t see a fontspec or even engine issue here, they are simply setting a value in the PDF file.

**Comment by wspr** [comment]
This seems definitive (thanks again) that there's nothing else for fontspec specifically to do here.

**Comment by rallg** [comment]
Thanks for looking into that. Reminds me: In PDF the decorations around hyperlinks are usually provided by the reader software.

**Comment by apoorvpotnis** [comment]
Is there a PDF viewer that the latex3 committee considers standard or canonical for their purposes, or uses it as the standard for their testing? 

I want to file 'bugs' to the PDF rendering engines, if rendering differently on different PDF viewers is indeed a bug according to the PDF standard. Is there actually an unambiguous way defined in the standard to render (to the last step of deciding which pixels on a given screen should be turned on and at what intensity) for a given PDF/glyph on the screen? If yes, then one can categorise the different renderings as bugs, I believe.

**Comment by davidcarlisle** [comment]
@apoorvpotnis  no. Due to the current focus on accessibility I use acrobat, foxit and firefox a lot but mostly in relation to screen reading, xpdf is my first choice pdf viewer, out of habit. Other team members will give different choices, especially those who have a Mac as their main machine. As I said in chat I think you will find that it is enough to report _differences_ in rendering. The developers can then work out whether they want to collectively clarify/follow the spec, or perhaps ignore the spec and just come to a collective agreement on behaviour.  Having a pdf that renders visibly differently in different systems is an indication of a bug somewhere.
